import fs from 'node:fs';
import path from 'node:path';

import type { CollabConfig } from './config';
import { ensureComposeEnvFile } from './compose-env';
import { type ComposeMode, getComposeFilePaths } from './compose-paths';
import type { EnvMap } from './env-file';
import type { Executor } from './executor';
import { sha256 } from './hash';
import type { Logger } from './logger';
import { loadState, saveState, toStateKey } from './state';
import { COMPOSE_ENV_DEFAULTS } from './compose-defaults';
import { consolidatedTemplate } from '../templates/consolidated';
import { infraTemplate } from '../templates/infra';
import { mcpTemplate } from '../templates/mcp';

const GENERATED_HEADER = '# Generated by collab-cli. Do not edit manually unless you accept drift warnings.\n\n';

export interface ComposeGenerationOptions {
  config: CollabConfig;
  mode: ComposeMode;
  outputDirectory?: string;
  outputFile?: string;
  envFile?: string;
  logger: Logger;
  executor: Executor;
}

export interface GeneratedComposeFile {
  filePath: string;
  content: string;
}

export interface ComposeGenerationResult {
  files: GeneratedComposeFile[];
  envFilePath: string;
  env: EnvMap;
  driftWarnings: string[];
}

function resolveEnvFilePath(config: CollabConfig, envFile?: string): string {
  return envFile ? path.resolve(config.workspaceDir, envFile) : config.envFile;
}

function renderContent(mode: ComposeMode): GeneratedComposeFile[] {
  if (mode === 'consolidated') {
    return [
      {
        filePath: '',
        content: `${GENERATED_HEADER}${consolidatedTemplate}`,
      },
    ];
  }

  return [
    {
      filePath: '',
      content: `${GENERATED_HEADER}${infraTemplate}`,
    },
    {
      filePath: '',
      content: `${GENERATED_HEADER}${mcpTemplate}`,
    },
  ];
}

function assignOutputPaths(
  files: GeneratedComposeFile[],
  config: CollabConfig,
  mode: ComposeMode,
  outputDirectory?: string,
  outputFile?: string,
): GeneratedComposeFile[] {
  const composePaths = getComposeFilePaths(config, outputDirectory);

  if (mode === 'consolidated') {
    const filePath = outputFile
      ? path.resolve(config.workspaceDir, outputFile)
      : composePaths.consolidated;

    return [
      {
        filePath,
        content: files[0].content,
      },
    ];
  }

  return [
    {
      filePath: composePaths.infra,
      content: files[0].content,
    },
    {
      filePath: composePaths.mcp,
      content: files[1].content,
    },
  ];
}

export function generateComposeFiles(options: ComposeGenerationOptions): ComposeGenerationResult {
  const envFilePath = resolveEnvFilePath(options.config, options.envFile);
  const env = ensureComposeEnvFile(envFilePath, options.logger, options.executor);

  const rendered = renderContent(options.mode);
  const files = assignOutputPaths(
    rendered,
    options.config,
    options.mode,
    options.outputDirectory,
    options.outputFile,
  );

  const state = loadState(options.config);
  const driftWarnings: string[] = [];

  for (const file of files) {
    options.executor.ensureDirectory(path.dirname(file.filePath));

    const stateKey = toStateKey(options.config, file.filePath);
    const previous = state.generatedFiles[stateKey];

    if (previous && fs.existsSync(file.filePath)) {
      const existingContent = fs.readFileSync(file.filePath, 'utf8');
      const existingHash = sha256(existingContent);
      if (existingHash !== previous.hash) {
        driftWarnings.push(
          `Manual edits detected in ${file.filePath}; file will be regenerated from templates.`,
        );
      }
    }

    options.executor.writeFile(file.filePath, file.content, { description: 'write compose file' });

    state.generatedFiles[stateKey] = {
      hash: sha256(file.content),
      generatedAt: new Date().toISOString(),
    };
  }

  saveState(options.config, state, options.executor);

  // Pre-create external Docker resources (network + volumes) so that
  // `docker compose up` succeeds even when run from a different project
  // directory.  These are no-ops when the resources already exist.
  ensureExternalDockerResources(env, options.executor);

  return {
    files,
    envFilePath,
    env,
    driftWarnings,
  };
}

function ensureExternalDockerResources(env: EnvMap, executor: Executor): void {
  const network = env.COLLAB_NETWORK || COMPOSE_ENV_DEFAULTS.COLLAB_NETWORK;
  const volumes = [
    env.QDRANT_VOLUME || COMPOSE_ENV_DEFAULTS.QDRANT_VOLUME,
    env.NEBULA_METAD_VOLUME || COMPOSE_ENV_DEFAULTS.NEBULA_METAD_VOLUME,
    env.NEBULA_STORAGED_VOLUME || COMPOSE_ENV_DEFAULTS.NEBULA_STORAGED_VOLUME,
    env.MCP_VOLUME || COMPOSE_ENV_DEFAULTS.MCP_VOLUME,
  ];

  // check: false — these are idempotent; "already exists" is not an error
  executor.run('docker', ['network', 'create', network], { verboseOnly: true, check: false });
  for (const vol of volumes) {
    executor.run('docker', ['volume', 'create', vol], { verboseOnly: true, check: false });
  }
}
