import fs from 'node:fs';
import path from 'node:path';

import { ensureWritableDirectory } from './preconditions';

export type EnvMap = Record<string, string>;

function parseEnvLine(line: string): [string, string] | null {
  const trimmed = line.trim();
  if (trimmed === '' || trimmed.startsWith('#')) {
    return null;
  }

  const index = trimmed.indexOf('=');
  if (index <= 0) {
    return null;
  }

  const key = trimmed.slice(0, index).trim();
  const value = trimmed.slice(index + 1);

  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
    return null;
  }

  return [key, value];
}

export function readEnvFile(filePath: string): EnvMap {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const content = fs.readFileSync(filePath, 'utf8');
  const env: EnvMap = {};

  for (const line of content.split(/\r?\n/)) {
    const parsed = parseEnvLine(line);
    if (parsed) {
      env[parsed[0]] = parsed[1];
    }
  }

  return env;
}

export function mergeEnvWithDefaults(existing: EnvMap, defaults: EnvMap): EnvMap {
  const merged: EnvMap = { ...defaults };

  for (const [key, value] of Object.entries(existing)) {
    merged[key] = value;
  }

  return merged;
}

export function writeEnvFile(filePath: string, env: EnvMap, keyOrder: readonly string[]): void {
  ensureWritableDirectory(path.dirname(filePath));

  const orderedKeys = new Set<string>();
  const lines: string[] = [];

  for (const key of keyOrder) {
    if (key in env) {
      lines.push(`${key}=${env[key]}`);
      orderedKeys.add(key);
    }
  }

  const customKeys = Object.keys(env)
    .filter((key) => !orderedKeys.has(key))
    .sort((a, b) => a.localeCompare(b));

  if (customKeys.length > 0) {
    lines.push('');
    for (const key of customKeys) {
      lines.push(`${key}=${env[key]}`);
    }
  }

  const rendered = `# Generated by collab-cli. You can edit values; regeneration preserves your overrides.\n${lines.join('\n')}\n`;
  fs.writeFileSync(filePath, rendered, 'utf8');
}
