export const changelogTemplate = `# Architecture Changelog

> Track of significant architectural changes over time.

## Format

Entries are ordered newest-first, grouped by date.

---

## [Unreleased]

- Initial canonical architecture scaffold generated by \`collab init\`.
`;

export const upgradeGuideTemplate = `# Upgrade Guide

> Instructions for migrating between canonical schema versions.

## Current Version: 1.0.0

This is the initial version. No migrations needed.

---

## Future Migrations

When the schema version changes, migration instructions will be
documented here with before/after examples.
`;

export const deprecatedTemplate = `# Deprecated Entries

> Canonical entries that have been superseded or invalidated.

When an axiom, decision, convention, or anti-pattern is no longer valid,
it is moved here with a rationale explaining why.

## Format

\`\`\`markdown
### <ID>: <Title>

**Deprecated:** YYYY-MM-DD
**Reason:** Why this entry was deprecated.
**Superseded by:** <new-ID> (if applicable)
\`\`\`

---

_No deprecated entries yet._
`;
