export const architecturePrTemplate = `# Generated by collab-cli — validates architecture docs on PRs.
name: Architecture Validation

on:
  pull_request:
    paths:
      - 'src/**'
      - 'docs/architecture/**'
      - '.collab/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Validate architecture
        run: npx @uxmaltech/collab-cli doctor --architecture
`;
