export const architectureMergeTemplate = `# Generated by collab-cli — re-ingests architecture docs on merge (indexed mode).
name: Architecture Ingestion

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/architecture/**'

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Ingest architecture docs
        run: npx @uxmaltech/collab-cli seed --architecture
        env:
          MCP_URL: \${{ secrets.MCP_URL }}
`;
