export const astDeltaPrTemplate = `# Generated by collab-cli — extracts delta AST on PRs and ingests into MCP.
name: AST Delta Extraction

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/**'
      - 'app/**'
      - 'lib/**'
      - 'packages/**'

jobs:
  ast-delta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Extract and ingest delta AST
        run: npx @uxmaltech/collab-cli ci ast-delta --base \${{ github.event.pull_request.base.sha }}
        continue-on-error: true
        env:
          MCP_BASE_URL: \${{ secrets.MCP_BASE_URL }}
          MCP_API_KEY: \${{ secrets.MCP_API_KEY }}
`;
