/**
 * Generates the canon-sync-trigger workflow template.
 * On merge to main, creates an issue in the business-canon repo.
 * Only generated for governed repos, NOT for the business-canon repo itself.
 */
export function canonSyncTriggerTemplate(canonOwnerRepo: string): string {
  return `# Generated by collab-cli — triggers canon sync on merge to main.
name: Canon Sync Trigger

on:
  push:
    branches: [main]

jobs:
  trigger-canon-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Create canon sync issue
        uses: actions/github-script@v7
        with:
          github-token: \${{ secrets.CANON_SYNC_PAT }}
          script: |
            const [owner, repo] = '${canonOwnerRepo}'.split('/');
            await github.rest.issues.create({
              owner, repo,
              title: 'Canon sync required — ' + context.repo.repo,
              body: '## Canon Sync Required\\n\\n'
                + 'Merge to \\\`main\\\` en **' + context.repo.owner + '/' + context.repo.repo + '**.\\n\\n'
                + '**Commit:** ' + context.sha + '\\n\\n'
                + '> Creado automáticamente por canon-sync-trigger.',
              labels: ['canon-sync', 'automated'],
            });
`;
}
