export const guardMainPrTemplate = `# Generated by collab-cli — blocks PRs to main that don't come from development.
name: Guard Main PR Source

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR comes from development
        if: github.event.pull_request.head.ref != 'development'
        run: |
          echo "::error::PRs to main must come from the development branch."
          exit 1
      - name: PR source is valid
        if: github.event.pull_request.head.ref == 'development'
        run: echo "PR is from development branch — allowed."
`;
