import fs from 'node:fs';
import path from 'node:path';

import { Command } from 'commander';

import { createCommandContext } from '../lib/command-context';
import { assertComposeFilesValid } from '../lib/compose-validator';
import { defaultCollabConfig, serializeUserConfig, type CollabConfig } from '../lib/config';
import { checkEcosystemCompatibility } from '../lib/ecosystem';
import { generateComposeFiles } from '../lib/compose-renderer';
import { CliError } from '../lib/errors';
import { parseMode, type CollabMode } from '../lib/mode';
import { runOrchestration } from '../lib/orchestrator';
import { promptBoolean, promptChoice } from '../lib/prompt';
import { assertPreflightChecks, runPreflightChecks } from '../lib/preflight';
import { ensureWritableDirectory } from '../lib/preconditions';
import { runDockerCompose } from '../lib/docker-compose';
import { resolveInfraComposeFile, runInfraCompose } from './infra/shared';
import { resolveMcpComposeFile, runMcpCompose } from './mcp/shared';
import type { ComposeMode } from '../lib/compose-paths';
import { assistantSetupStage } from '../stages/assistant-setup';
import { canonScaffoldStage } from '../stages/canon-scaffold';
import { canonIngestStage } from '../stages/canon-ingest';
import { getEnabledProviders, PROVIDER_DEFAULTS, type ProviderKey } from '../lib/providers';

interface InitOptions {
  force?: boolean;
  yes?: boolean;
  resume?: boolean;
  mode?: string;
  composeMode?: string;
  outputDir?: string;
  skipMcpSnippets?: boolean;
  ingest?: boolean;
  timeoutMs?: string;
  retries?: string;
  retryDelayMs?: string;
  providers?: string;
}

interface WizardSelection {
  mode: CollabMode;
  composeMode: ComposeMode;
  runIngestBootstrap: boolean;
}

function parseComposeMode(value: string | undefined, fallback: ComposeMode = 'consolidated'): ComposeMode {
  if (!value) {
    return fallback;
  }

  if (value === 'consolidated' || value === 'split') {
    return value;
  }

  throw new CliError(`Invalid compose mode '${value}'. Use 'consolidated' or 'split'.`);
}

function toNumber(value: string | undefined, fallback: number): number {
  if (!value) {
    return fallback;
  }

  const parsed = Number.parseInt(value, 10);
  return Number.isNaN(parsed) ? fallback : parsed;
}

function inferComposeMode(config: CollabConfig): ComposeMode {
  const infraPath = path.resolve(config.workspaceDir, config.compose.infraFile);
  const mcpPath = path.resolve(config.workspaceDir, config.compose.mcpFile);

  if (fs.existsSync(infraPath) && fs.existsSync(mcpPath)) {
    return 'split';
  }

  return 'consolidated';
}

async function resolveWizardSelection(
  options: InitOptions,
  config: CollabConfig,
): Promise<WizardSelection> {
  const defaults: WizardSelection = {
    mode: parseMode(options.mode, config.mode),
    composeMode: parseComposeMode(options.composeMode, inferComposeMode(config)),
    runIngestBootstrap: Boolean(options.ingest),
  };

  if (options.yes) {
    return {
      ...defaults,
      mode: options.mode ? parseMode(options.mode) : 'file-only',
      composeMode: options.composeMode ? parseComposeMode(options.composeMode) : 'consolidated',
      runIngestBootstrap: Boolean(options.ingest),
    };
  }

  const mode = options.mode
    ? parseMode(options.mode)
    : await promptChoice(
        'Select setup mode:',
        [
          { value: 'file-only', label: 'file-only (skip infra + MCP startup)' },
          { value: 'indexed', label: 'indexed (start infra + MCP and enable retrieval)' },
        ],
        defaults.mode,
      );

  // Skip compose-mode prompt when mode is file-only — no Docker/MCP
  // infrastructure is used, so compose configuration is irrelevant.
  const composeMode =
    mode === 'file-only'
      ? parseComposeMode(options.composeMode, 'consolidated')
      : options.composeMode
        ? parseComposeMode(options.composeMode)
        : await promptChoice(
            'Select compose generation mode:',
            [
              { value: 'consolidated', label: 'consolidated (single docker-compose.yml)' },
              { value: 'split', label: 'split (infra + mcp compose files)' },
            ],
            defaults.composeMode,
          );

  const runIngestBootstrap =
    mode === 'indexed'
      ? options.ingest
        ? true
        : await promptBoolean('Run ingest bootstrap command after startup?', defaults.runIngestBootstrap)
      : false;

  return {
    mode,
    composeMode,
    runIngestBootstrap,
  };
}

function renderMcpSnippet(provider: ProviderKey, config: CollabConfig): { filename: string; content: string } {
  const workspace = config.workspaceDir;
  const mcpUrl = 'http://127.0.0.1:7337/mcp';

  switch (provider) {
    case 'codex':
      return {
        filename: 'codex-mcp-config.toml',
        content: [
          '# Generated by collab-cli',
          '[mcp_servers.collab_architecture]',
          'transport = "http"',
          `url = "${mcpUrl}"`,
          '',
          '# If MCP_API_KEYS is configured, set a bearer token header in your client.',
          '# headers = { Authorization = "Bearer <token>" }',
          '',
          `# Workspace: ${workspace}`,
          '',
        ].join('\n'),
      };

    case 'claude':
      return {
        filename: 'claude-mcp-config.json',
        content: JSON.stringify(
          {
            _comment: 'Generated by collab-cli — merge into your Claude Code MCP settings',
            mcpServers: {
              'collab-architecture': {
                type: 'url',
                url: mcpUrl,
              },
            },
          },
          null,
          2,
        ) + '\n',
      };

    case 'gemini':
      return {
        filename: 'gemini-mcp-config.json',
        content: JSON.stringify(
          {
            _comment: 'Generated by collab-cli — merge into your Gemini MCP settings',
            mcpServers: {
              'collab-architecture': {
                type: 'url',
                url: mcpUrl,
              },
            },
          },
          null,
          2,
        ) + '\n',
      };
  }
}

export function registerInitCommand(program: Command): void {
  program
    .command('init')
    .description('Run onboarding wizard and orchestrate setup stages')
    .option('-f, --force', 'Overwrite existing .collab/config.json with new wizard selection')
    .option('--yes', 'Accept wizard defaults and run non-interactively')
    .option('--resume', 'Resume from the last incomplete wizard stage')
    .option('--mode <mode>', 'Wizard mode: file-only|indexed')
    .option('--compose-mode <mode>', 'Compose mode: consolidated|split')
    .option('--output-dir <directory>', 'Directory used to write compose outputs')
    .option('--skip-mcp-snippets', 'Skip MCP client config snippet generation')
    .option('--ingest', 'Run optional ingest bootstrap stage (indexed mode only)')
    .option('--providers <list>', 'Comma-separated AI provider list (codex,claude,gemini)')
    .option('--timeout-ms <ms>', 'Per-check timeout in milliseconds', '5000')
    .option('--retries <count>', 'Health check retries', '15')
    .option('--retry-delay-ms <ms>', 'Delay between retries in milliseconds', '2000')
    .addHelpText(
      'after',
      `
Examples:
  collab init
  collab init --yes
  collab init --yes --mode file-only
  collab init --resume
`,
    )
    .action(async (options: InitOptions, command: Command) => {
      const context = createCommandContext(command);
      ensureWritableDirectory(context.config.workspaceDir);
      const configExistedBefore = fs.existsSync(context.config.configFile);

      if (options.force) {
        context.logger.warn('Force mode enabled: configuration will be overwritten with wizard selections.');
      }

      const selections = await resolveWizardSelection(options, context.config);
      const health = {
        timeoutMs: toNumber(options.timeoutMs, 5_000),
        retries: toNumber(options.retries, 15),
        retryDelayMs: toNumber(options.retryDelayMs, 2_000),
      };

      const effectiveConfig: CollabConfig = {
        ...defaultCollabConfig(context.config.workspaceDir),
        ...context.config,
        mode: selections.mode,
      };

      await runOrchestration(
        {
          workflowId: 'init',
          config: effectiveConfig,
          executor: context.executor,
          logger: context.logger,
          resume: options.resume,
          stageOptions: {
            yes: options.yes,
            providers: options.providers,
            outputDir: options.outputDir,
          },
        },
        [
          {
            id: 'preflight',
            title: 'Run preflight checks',
            recovery: [
              'Install missing dependencies reported by preflight.',
              'Run collab init --resume after fixing prerequisites.',
            ],
            run: () => {
              const checks = runPreflightChecks(context.executor);
              assertPreflightChecks(checks, context.logger);
            },
          },
          {
            id: 'environment-setup',
            title: 'Write local collab configuration',
            recovery: [
              'Verify write permissions for .collab and workspace directory.',
              'Run collab init --resume once permissions are fixed.',
            ],
            run: () => {
              if (configExistedBefore && !options.force) {
                context.logger.info(
                  'Existing configuration detected; preserving it. Use --force to overwrite.',
                );
                return;
              }

              context.executor.ensureDirectory(effectiveConfig.collabDir);
              context.executor.writeFile(
                effectiveConfig.configFile,
                `${serializeUserConfig(effectiveConfig)}\n`,
                { description: 'write collab config' },
              );
            },
          },
          assistantSetupStage,
          canonScaffoldStage,
          {
            id: 'compose-generation',
            title: 'Generate and validate compose files',
            recovery: [
              'Run collab compose validate to inspect configuration errors.',
              'Run collab init --resume after fixing compose inputs.',
            ],
            run: () => {
              if (selections.mode === 'file-only') {
                context.logger.info('Mode file-only selected; skipping compose generation stage.');
                return;
              }

              const generation = generateComposeFiles({
                config: effectiveConfig,
                mode: selections.composeMode,
                outputDirectory: options.outputDir,
                logger: context.logger,
                executor: context.executor,
              });

              for (const warning of generation.driftWarnings) {
                context.logger.warn(warning);
              }

              assertComposeFilesValid(
                generation.files.map((file) => file.filePath),
                effectiveConfig.workspaceDir,
                context.executor,
              );
            },
          },
          {
            id: 'infra-start',
            title: 'Start infrastructure services',
            recovery: [
              'Run collab infra status to inspect Qdrant and Nebula.',
              'Run collab init --resume after infra services are healthy.',
            ],
            run: async () => {
              if (selections.mode === 'file-only') {
                context.logger.info('Mode file-only selected; skipping infra startup stage.');
                return;
              }

              const selection = resolveInfraComposeFile(effectiveConfig, options.outputDir, undefined);
              await runInfraCompose(
                context.logger,
                context.executor,
                effectiveConfig,
                selection,
                'up',
                { health },
              );
            },
          },
          {
            id: 'mcp-start',
            title: 'Start MCP service',
            recovery: [
              'Run collab mcp status to inspect MCP runtime.',
              'Run collab init --resume after MCP health endpoint responds.',
            ],
            run: async () => {
              if (selections.mode === 'file-only') {
                context.logger.info('Mode file-only selected; skipping MCP startup stage.');
                return;
              }

              const selection = resolveMcpComposeFile(effectiveConfig, options.outputDir, undefined);
              await runMcpCompose(
                context.logger,
                context.executor,
                effectiveConfig,
                selection,
                'up',
                { health },
              );
            },
          },
          {
            id: 'mcp-client-config',
            title: 'Generate MCP client config snippets',
            recovery: [
              'Verify permissions in .collab directory.',
              'Run collab init --resume to regenerate MCP config snippets.',
            ],
            run: () => {
              if (selections.mode === 'file-only') {
                context.logger.info('Mode file-only selected; skipping MCP snippet generation.');
                return;
              }

              if (options.skipMcpSnippets) {
                context.logger.info('Skipping MCP snippet generation by user choice.');
                return;
              }

              const enabled = getEnabledProviders(effectiveConfig);
              if (enabled.length === 0) {
                context.logger.info('No providers configured; skipping MCP snippet generation.');
                return;
              }

              for (const provider of enabled) {
                const snippet = renderMcpSnippet(provider, effectiveConfig);
                const target = path.join(effectiveConfig.collabDir, snippet.filename);
                context.executor.writeFile(target, snippet.content, {
                  description: `write ${PROVIDER_DEFAULTS[provider].label} MCP config snippet`,
                });
              }

              context.logger.info(
                `Generated MCP snippets for: ${enabled.map((k) => PROVIDER_DEFAULTS[k].label).join(', ')}`,
              );
            },
          },
          canonIngestStage,
          {
            id: 'ingest-bootstrap',
            title: 'Optional ingest bootstrap',
            recovery: [
              'Ensure MCP container is running before ingestion.',
              'Run collab init --resume to retry ingest bootstrap.',
            ],
            run: () => {
              if (selections.mode === 'file-only') {
                context.logger.info('Mode file-only selected; skipping ingest bootstrap stage.');
                return;
              }

              if (!selections.runIngestBootstrap) {
                context.logger.info('Skipping ingest bootstrap stage by user choice.');
                return;
              }

              const selection = resolveMcpComposeFile(effectiveConfig, options.outputDir, undefined);
              runDockerCompose({
                executor: context.executor,
                files: [selection.filePath],
                arguments: ['exec', 'mcp', 'npm', 'run', 'ingest:v2'],
                cwd: effectiveConfig.workspaceDir,
              });
            },
          },
        ],
      );

      const compatibility = await checkEcosystemCompatibility(effectiveConfig, {
        dryRun: context.executor.dryRun,
      });

      context.logger.result('');
      context.logger.result('Wizard summary');
      context.logger.result(`- mode: ${selections.mode}`);
      context.logger.result(`- compose mode: ${selections.composeMode}`);
      context.logger.result(`- dry-run: ${context.executor.dryRun ? 'yes' : 'no'}`);
      context.logger.result(`- config: ${effectiveConfig.configFile}`);
      context.logger.result(`- env: ${effectiveConfig.envFile}`);

      const enabledProviders = getEnabledProviders(effectiveConfig);
      if (enabledProviders.length > 0) {
        const providerLabels = enabledProviders.map((k) => PROVIDER_DEFAULTS[k].label);
        context.logger.result(`- providers: ${providerLabels.join(', ')}`);
      } else {
        context.logger.result('- providers: (none configured)');
      }

      for (const check of compatibility) {
        const prefix = check.ok ? '[PASS]' : '[WARN]';
        context.logger.result(`${prefix} ${check.id}: ${check.detail}`);
        if (!check.ok && check.fix) {
          context.logger.result(`       fix: ${check.fix}`);
        }
      }

      if (!options.force && configExistedBefore) {
        context.logger.debug('Existing configuration was reused.');
      }
    });
}
