import fs from 'node:fs';
import path from 'node:path';

import type { OrchestrationStage, StageContext } from '../lib/orchestrator';

const PLACEHOLDER_MARKER = '<!-- AI-GENERATED: PLACEHOLDER -->';

interface RepoScaffoldEntry {
  relativePath: string;
  content: string;
}

function buildRepoScaffoldEntries(): RepoScaffoldEntry[] {
  return [
    {
      relativePath: 'knowledge/axioms/README.md',
      content: [
        '# Axioms',
        '',
        PLACEHOLDER_MARKER,
        '',
        'Project-specific foundational truths. Generated by AI analysis or written manually.',
        '',
        '## Adding Axioms',
        '',
        'Each axiom should have:',
        '- A unique ID (e.g., `AX-001`)',
        '- A confidence level (`experimental | provisional | verified`)',
        '- A clear statement and rationale',
        '',
      ].join('\n'),
    },
    {
      relativePath: 'knowledge/decisions/README.md',
      content: [
        '# Architecture Decision Records',
        '',
        PLACEHOLDER_MARKER,
        '',
        'Project-specific ADRs. Follow the format:',
        '',
        '- **Context**: What prompted the decision',
        '- **Decision**: What was decided',
        '- **Consequences**: Trade-offs and outcomes',
        '',
      ].join('\n'),
    },
    {
      relativePath: 'knowledge/conventions/README.md',
      content: [
        '# Conventions',
        '',
        PLACEHOLDER_MARKER,
        '',
        'Project-specific naming, versioning, and code conventions.',
        '',
      ].join('\n'),
    },
    {
      relativePath: 'knowledge/anti-patterns/README.md',
      content: [
        '# Anti-Patterns',
        '',
        PLACEHOLDER_MARKER,
        '',
        'Documented violations and patterns to avoid in this project.',
        '',
      ].join('\n'),
    },
    {
      relativePath: 'domains/README.md',
      content: [
        '# Domains',
        '',
        PLACEHOLDER_MARKER,
        '',
        'Project-specific domain boundaries, responsibilities, and public APIs.',
        '',
      ].join('\n'),
    },
  ];
}

function generateRepoScaffold(ctx: StageContext): void {
  const repoDir = ctx.config.repoDir;
  const entries = buildRepoScaffoldEntries();

  let created = 0;
  let skipped = 0;

  for (const entry of entries) {
    const target = path.join(repoDir, entry.relativePath);

    if (!ctx.executor.dryRun && fs.existsSync(target)) {
      ctx.logger.debug(`Repo scaffold file already exists, skipping: ${entry.relativePath}`);
      skipped++;
      continue;
    }

    ctx.executor.ensureDirectory(path.dirname(target));
    ctx.executor.writeFile(target, entry.content, {
      description: `scaffold repo/${entry.relativePath}`,
    });
    created++;
  }

  ctx.logger.info(
    `Repo scaffold: ${created} file(s) created, ${skipped} existing file(s) preserved.`,
  );
}

export const repoScaffoldStage: OrchestrationStage = {
  id: 'repo-scaffold',
  title: 'Generate project architecture scaffold',
  recovery: [
    'Verify write permissions for docs/architecture/repo/ directory.',
    'Run collab init --resume to retry scaffold generation.',
  ],
  run: (ctx) => {
    generateRepoScaffold(ctx);
  },
};
