import type { CollabConfig } from '../../lib/config';
import { checkEcosystemCompatibility, getMcpContractRange } from '../../lib/ecosystem';
import { CliError } from '../../lib/errors';
import { loadGitHubAuth, isGitHubAuthValid, runGitHubDeviceFlow, storeGitHubToken } from '../../lib/github-auth';
import { probeMcpContract } from '../../lib/mcp-contract';
import type { OrchestrationStage } from '../../lib/orchestrator';
import type { ProviderKey } from '../../lib/providers';
import type { Logger } from '../../lib/logger';

import type { InitOptions } from './types';

export function renderMcpSnippet(provider: ProviderKey, config: CollabConfig): { filename: string; content: string } | null {
  const workspace = config.workspaceDir;
  const mcpUrl = config.mcpUrl
    ? `${config.mcpUrl}/mcp`
    : 'http://127.0.0.1:7337/mcp';

  switch (provider) {
    case 'codex':
      return {
        filename: 'codex-mcp-config.toml',
        content: [
          '# Generated by collab-cli',
          '[mcp_servers.collab_architecture]',
          'transport = "http"',
          `url = "${mcpUrl}"`,
          '',
          '# If MCP_API_KEYS is configured, set a bearer token header in your client.',
          '# headers = { Authorization = "Bearer <token>" }',
          '',
          `# Workspace: ${workspace}`,
          '',
        ].join('\n'),
      };

    case 'claude':
      return {
        filename: 'claude-mcp-config.json',
        content: JSON.stringify(
          {
            _comment: 'Generated by collab-cli — merge into your Claude Code MCP settings',
            mcpServers: {
              'collab-architecture': {
                type: 'url',
                url: mcpUrl,
              },
            },
          },
          null,
          2,
        ) + '\n',
      };

    case 'gemini':
      return {
        filename: 'gemini-mcp-config.json',
        content: JSON.stringify(
          {
            _comment: 'Generated by collab-cli — merge into your Gemini MCP settings',
            mcpServers: {
              'collab-architecture': {
                type: 'url',
                url: mcpUrl,
              },
            },
          },
          null,
          2,
        ) + '\n',
      };

    case 'copilot':
      // Copilot doesn't use MCP config snippets
      return null;
  }
}

export async function validateMcpServerContract(
  mcpUrl: string,
  logger: Logger,
  dryRun: boolean,
): Promise<void> {
  const result = await probeMcpContract(mcpUrl, {
    contractRange: getMcpContractRange(),
    dryRun,
  });

  if (result.skipped) {
    logger.info('[dry-run] Skipped MCP contract validation.');
    return;
  }

  if (!result.ok) {
    throw new CliError(result.error ?? `MCP contract validation failed for ${mcpUrl}`);
  }

  const health = result.health!;
  logger.step(true, `MCP server reachable at ${mcpUrl}`);
  logger.info(`Server version: ${health.version}`);
  logger.info(`Contract version: ${health.contractVersion}`);

  const deps = Object.entries(health.dependencies)
    .map(([name, status]) => `${name} (${status})`)
    .join(', ');
  if (deps) {
    logger.info(`Dependencies: ${deps}`);
  }

  if (result.contractCompatible === false) {
    logger.warn(
      `MCP contract version ${health.contractVersion} may be incompatible ` +
      `(CLI expects ${getMcpContractRange()}). Some features may not work correctly.`,
    );
  }

  const degraded = Object.entries(health.dependencies)
    .filter(([, status]) => status !== 'up');
  if (degraded.length > 0) {
    const names = degraded.map(([name, status]) => `${name} (${status})`).join(', ');
    logger.warn(`Some MCP dependencies are not fully ready: ${names}`);
  }
}

export function buildGitHubAuthStage(
  effectiveConfig: CollabConfig,
  logger: Logger,
  options: InitOptions,
): OrchestrationStage {
  return {
    id: 'github-auth',
    title: 'Authorize GitHub access',
    recovery: [
      'Set COLLAB_GITHUB_CLIENT_ID env var if OAuth App is not configured.',
      'Use --github-token <token> to provide a token directly.',
      'Run collab init --resume after fixing GitHub access.',
    ],
    run: async () => {
      // Skip GitHub auth when no GitHub canon is configured.
      // In indexed mode, a GitHub canon is always required (enforced
      // by parseBusinessCanonOption), so this check only triggers in
      // file-only mode or when preserving an existing config.
      const canon = effectiveConfig.canons?.business;
      if (!canon || canon.source === 'local') {
        logger.info('No GitHub canon configured; skipping GitHub authorization.');
        return;
      }

      // Check for pre-existing valid token
      const existing = loadGitHubAuth(effectiveConfig.collabDir);
      if (existing) {
        const valid = await isGitHubAuthValid(existing);
        if (valid) {
          logger.info('GitHub authorization already configured and valid.');
          return;
        }
        logger.info('Existing GitHub token is invalid or expired. Re-authorizing...');
      }

      // --github-token flag: store directly
      if (options.githubToken) {
        storeGitHubToken(effectiveConfig.collabDir, options.githubToken);
        logger.info('GitHub token stored from --github-token flag.');
        return;
      }

      // --yes without token: fail
      if (options.yes) {
        throw new CliError(
          'GitHub authorization required. Use --github-token <token> in non-interactive mode.',
        );
      }

      // Interactive: run Device Flow
      await runGitHubDeviceFlow(effectiveConfig.collabDir, (msg) => logger.info(msg));
    },
  };
}

export async function runEcosystemChecks(
  config: CollabConfig,
  logger: Logger,
  dryRun: boolean,
): Promise<void> {
  const compatibility = await checkEcosystemCompatibility(config, { dryRun });
  for (const check of compatibility) {
    const prefix = check.ok ? '[PASS]' : '[WARN]';
    logger.result(`${prefix} ${check.id}: ${check.detail}`);
    if (!check.ok && check.fix) {
      logger.result(`       fix: ${check.fix}`);
    }
  }
}
